Issue #58 - Feature Request: Create build pipeline to build and publi…
open-horizon/vault-exchange-auth pull request #59
Opened 2023-06-20 21:57 UTC by blakep7

…sh Vault container image

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- Added GitHub action workflow 'build-push' to build docker image and push it to Dockerhub

**Necessary Repository Secrets and Variables**
_Found in: Repo Settings -> Secrets and Variables -> Actions_

- Secrets
   - DOCKER_USER: Username for docker login
   - DOCKER_TKN: Token for docker login
- Variables
   - DOCKERHUB_REPO: openhorizon

Fixes #58

2023-06-21 14:10 UTC, bencourliss requested changes

2023-06-21 14:10 UTC, bencourliss commented on .github/workflows/build-push.yml
> +          VERSION: '${{ steps.config-version.outputs.VERSION }}-${{ github.run_number }}'
See if https://github.com/marketplace/actions/build-tag-number allows us to set an arbitrary build number.

2023-06-21 22:20 UTC, blakep7 commented on .github/workflows/build-push.yml
> +          VERSION: '${{ steps.config-version.outputs.VERSION }}-${{ github.run_number }}'
Added a repo variable that we can configure to offset the run number. 'RUN_NUMBER_OFFSET'

2023-06-22 19:42 UTC, blakep7 commented
Changed: Workflow uses secret 'DOCKER_TOKEN' now.

2023-07-07 19:04 UTC, bencourliss approved these changes

2023-07-07 19:04 UTC, merged