Fix image vulnerabilities
open-horizon/vault-exchange-auth pull request #76
Opened 2024-12-05 09:56 UTC by K-Pomian

Fix #75

2024-12-05 15:22 UTC, omordyk requested changes

2024-12-05 15:22 UTC, omordyk commented on go.mod
> +	github.com/docker/docker v25.0.6+incompatible // indirect
@K-Pomian pls rebase on my PR: https://github.com/open-horizon/vault-exchange-auth/pull/78
We need version of **github.com/docker/docker** no lower than v26.1.5.

2024-12-05 15:22 UTC, omordyk commented
Should be merged after https://github.com/open-horizon/vault-exchange-auth/pull/78

2024-12-10 14:36 UTC, bencourliss requested changes

2024-12-10 14:36 UTC, bencourliss commented on Makefile
> +VAULT_VERSION ?= 1.14.13+ent
I think we need to be at 1.14.10 non-enterprise version.

2024-12-10 16:30 UTC, bencourliss commented
> @bencourliss I recall that vault version we are locked for is v1.14.9?

We're locked to the minor version. So any patch of 1.14 is fine.

2024-12-10 16:32 UTC, bencourliss approved these changes
LGTM

2024-12-10 16:33 UTC, merged

2025-01-02 13:21 UTC, naphelps commented
@K-Pomian This PR needs to be backed out of the history. Vault needs to be downgraded to and locked to 1.14.8.

2025-01-02 17:34 UTC, naphelps commented
I fixed the source and history with a forced rebase. 8b702434a7b5478636b6ed613760a72d79c50879

The fixed container runs in a local all-in-one. The dockerhub testing tag has been updated. The version tag still needs to be rebuilt.